export const GET_INGREDIENTS_CONSTRUCTOR_BUN = 'GET_INGREDIENTS_CONSTRUCTOR_BUN';
export const GET_INGREDIENTS_CONSTRUCTOR_MAIN = 'GET_INGREDIENTS_CONSTRUCTOR_MAIN';
export const ADD_INGREDIENTS_CONSTRUCTOR_MAIN ="ADD_INGREDIENTS_CONSTRUCTOR_MAIN";
export const RESET_INGREDIENTS_CONSTRUCTOR ="RESET_INGREDIENTS_CONSTRUCTOR";
