export const GET_DATA_API = 'GET_DATA_API';
export const GET_DATA_API_FAILED = 'GET_DATA_API_FAILED';
export const GET_DATA_API_SUCCESS = 'GET_DATA_API_SUCCESS';
export const SET_DATA_API= 'SET_DATA_API';



