export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const GET_INGREDIENTS_CONSTRUCTOR = 'GET_INGREDIENTS_CONSTRUCTOR';
export const GET_SELECTED_INGREDIENT = 'GET_CURRENT_INGREDIENT';
export const GET_ORDER = 'GET_ORDER';

